import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "../context/SocketProvider";
import { AuthProvider } from "@/context/AuthContext";
const poppins = Poppins({ weight: ["400", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatApp",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <SocketProvider>
          <body className={poppins.className}>{children}</body>
        </SocketProvider>
      </AuthProvider>
    </html>
  );
}
